### ISSUE TITLE
Shouldn't `diff([], ['a'])` be `[]`?

### ISSUE THREAD

**Issue by gustavopch** [rayepps/radash#107]
Code: `diff([], ['a'])`
Expected result: `[]`
Actual result: `['a']`

The description of the function is:
> Given two arrays, returns an array of all items that exist in the first array but do not exist in the second array.
> – https://radash-docs.vercel.app/docs/array-diff

In other words, an item should be included in the result if:
- it exists in the first array, and
- it doesn't exist in the second array.

The first condition is not met for `'a'`, therefore it should not be included in the result.

If my logic is right, then [this line](https://github.com/rayepps/radash/blob/master/src/array.ts#L398) should be changed to `if (!root?.length) return []` and [this test case](https://github.com/rayepps/radash/blob/master/src/tests/array.test.ts#L509-L512) should be changed to `assert.deepEqual(result, [])`. It's how Lodash's [`difference()`](https://lodash.com/docs/4.17.15#difference) works by the way.

Version 8 seems to be around the corner, so it seems like a good time for such a breaking change.

**Comment by rayepps** [comment]
Great call out @gustavopch I'll be sure to fix this and get it out in v8.0.0 👍

**Comment by rayepps** [comment]
This was just published in `v8.0.1` 🎉
