### ISSUE TITLE
Drop support for node v12

### ISSUE THREAD

**Issue by rayepps** [rayepps/radash#109]
Based on chat with @matteosacchetto in #108 we'll drop support for node 12 after node v18 becomes LTS on `2022-10-25`. This will be a major version bump to `9.0.0`.

<img width="893" alt="Screen Shot 2022-10-18 at 9 35 28 AM" src="https://user-images.githubusercontent.com/15269623/196490321-3a4eaff8-1760-42e3-bd18-791dc0d92e7b.png">

See Node release calendar [here](https://github.com/nodejs/Release).

**Comment by matteosacchetto** [comment]
I would also suggest, already for release 8.0.0, adding to the package JSON the detail about the minimum supported node version, with the `engines` property. Reference [here](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines)

Example:
```json
{
  ...,
  "engines": {
    "node": ">=12.22.12"
  }
}
```

`12.22.12` is the LTS version used in the test runners github actions

**Comment by MarlonPassos-git** [comment]
shouldn't you change the ci test versions too?
```
  ...
  node-version: [14.x, 16.x, 18.x]
```

**Comment by matteosacchetto** [comment]
Yes. When we will drop support for v12 there will be changes regarding Rollup, tsconfig, the ci tests and the engine specified in the package.json

As soon as node 18 lands as an LTS il will do a PR with those changes
