### ISSUE TITLE
_.try is incompatible with AWS SDK v3

### ISSUE THREAD

**Issue by kpeters-cbsi** [rayepps/radash#123]
Typescript 4.8.4
Radash 8.0.3-alpha.1

This may be related to #60 

If I'm reading the documentation for `_.try` correctly, the following two code snippets should be (roughly) functionally identical

```
// try/catch
import { S3Client, GetObjectCommand, GetObjectCommandInput } from '@aws-sdk/client-s3';

const params = {
  Bucket: 'my-bucket',
  Key: 'my-key'
};

const s3client = new S3Client({});

let [res, err];
try {
  res = await s3client.send(new GetObjectCommand(params));
} catch (e) {
  err = e;
}
```

```
// _.try
import { S3Client, GetObjectCommand, GetObjectCommandInput } from '@aws-sdk/client-s3';

const params = {
  Bucket: 'my-bucket',
  Key: 'my-key'
};

const s3client = new S3Client({});

const [res, err] = _.try(s3client.send)(new GetObjectCommand(params));
```

However, with the latter construction, Typescript brings up the error: `Expected 3 arguments, but got 1. ts(2554)`

I tried the workaround listed in #60: 

```
 const [err, res] = await _.try(async () => await s3client.send(new GetObjectCommand(params)))
```

But that produced the error `Type '() => Promise<[Error, null] | [null, GetObjectCommandOutput]>' must have a '[Symbol.iterator]()' method that returns an iterator. ts(2488)`. 

Any thoughts on how I could use `_.try` with AWS SDK v3?

**Comment by rayepps** [comment]
On this last example, you need to call the function. `try` returns a function to be called.
```ts
const [err, res] = await _.try(async () => await s3client.send(new GetObjectCommand(params)))
```
this ^^^ becomes vvv
```ts
const [err, res] = await _.try(async () => await s3client.send(new GetObjectCommand(params)))()
```

**Comment by kpeters-cbsi** [comment]
That did it, paving the way for #125 ... :\
