### ISSUE TITLE
feature request: `Array.removeOrAppend`

### ISSUE THREAD

**Issue by rolule** [rayepps/radash#137]
A common use case with implementing toggle filters in a UI is to add the active filters to an array. Let's say we want to filter a list of items by color, and we can have multiple color filters active at the same time.

```ts
type Filter = 'red' | 'blue' | 'green'

const activeFilters: Filter[] = ['red', 'blue']
```

Now when the user deselects the `red` filter, we want to remove it from the array of `activeFilters`. We could do that using `Array.filter`. And when the user selects the `red` filter again, it should be added back to the list. Because the order of the filters does not matter, we can append. The implementation for this could look like this (imagine setActiveFilters to trigger a state update like in React):

```ts
const handleFilterToggle = (filter: Filter) => {
  // deselect the filter if it is active
  if(activeFilters.includes(filter)) {
    setActiveFilters(activeFilters.filter(f => f !== filter))
  } else {
    // append the filter to activeFilters
    setActiveFilters([...activeFilters, filter])
  }
}
```

It would be quite useful to have this implementation as a dedicated function that could be called something like `toggleItem` or `removeOrAppend`. The proposed function signature could look like this: 

```ts
removeOrAppend(list, item, compareFn?: (item) => any)
```

 where list is the given array, item is the element to remove or append and compareFn is a an optional function that can be passed in to determine an item's identity like in `unique`.

Example usage: 

```ts
const activeFilters: Filter[] = ['red', 'blue']

const removedRed = removeOrAppend(activeFilters, 'red') // ['blue']
const addedGreen = removeOrAppend(activeFilters, 'green') // ['blue', 'green']
```

I would love this to be a function as it is quite a common use case. Please let me know your opinion on this :)

**Comment by rayepps** [comment]
Hey @rolule thanks for bringing this up! I like the idea. Its a small simple function that will fit well into the array module.

One thing, do you think it's a stretch to call it `toggle`?

**Comment by rolule** [comment]
Hey @rayepps, sorry for not responding. I like the name `toggle`. Maybe then we should also include an option, if we want to append or prepend the item?

**Comment by rayepps** [comment]
No worries! Sweet, stoked you like `toggle`, I think its a great name. Ya that makes sense, I'd be down for a config that lets you specify append or prepend.

**Comment by rolule** [comment]
Thank you again for the addition of toggle! :) 
btw I wanted to ask here instead of opening a new issue right away: is it a design decision that no `Array.remove` function is included in radash? I personally find it cumbersome to always use `filter` to remove an item.

**Comment by rayepps** [comment]
> is it a design decision that no `Array.remove` function is included in radash?

No, not a design decision just haven't personally had the need and haven't had anyone request it. Seems like a good fit though.

**Comment by rayepps** [comment]
The `toggle` function is now out in `v9.1.0` 🎉
