### ISSUE TITLE
Could this awesome library be also available via CDN? 

### ISSUE THREAD

**Issue by MartinStrekelj** [rayepps/radash#140]
Basically title, I love the library but in my current use-case (due to some limitations) I would like to inject it into a plain HTML site.

Thanks in advance.

**Comment by rayepps** [comment]
Hi @MartinStrekelj 👋 I think that's a great idea! I did the work to update the project to build the output files for CDN. After that's merged I'll put it on a CDN -- not sure which one yet 🤔

**Comment by rayepps** [comment]
I've updated our build/ci to build cdn ready files. Just need to do a release (planning for tonight). After the release you'll be able to use jsdeliver. We're working on cdnjs ([#1392](https://github.com/cdnjs/packages/issues/1392)) so hopefully have that setup soon as well.

**Comment by rayepps** [comment]
Ok, so took a bit to get a release ready change together but it's out and so is our first cdn available version 🎉 

```
<script src="https://cdn.jsdelivr.net/gh/rayepps/radash@v9.1.0/cdn/radash.js"></script>
```
