### ISSUE TITLE
Radash Playground CodeSandbox shows 502 error

### ISSUE THREAD

**Issue by Starboy-Sharma** [rayepps/radash#17]
I have tried to open Radash playground it redirects me to the code sandbox where it shows me a 502 error. I try to change some code to see the effect but nothing happens feels like it is broken. I have tried this playground in Chrome and Firefox.

![image](https://user-images.githubusercontent.com/31812684/186829668-b61ea193-d653-4d4b-81c6-5c1901960533.png)

**Comment by rayepps** [comment]
This has been fixed! I changed the playground from codesandbox to runkit because I couldn't get codesandbox to work correctly.
