### ISSUE TITLE
Broken search input design on focus 

### ISSUE THREAD

**Issue by Starboy-Sharma** [rayepps/radash#18]
I am using Firefox Browser I have noticed two things
1. In responsive mode when I click on the search input box it shows me as shown below
![image](https://user-images.githubusercontent.com/31812684/186830660-da9247c3-5561-459f-a87c-6dbed2a322a9.png)

2. I have noticed a c text near search input in desktop view
![image](https://user-images.githubusercontent.com/31812684/186830919-a05a5eb1-e97f-402b-a4f3-64d9e8c96dc4.png)

**Comment by Starboy-Sharma** [comment]
I can fix these issues. But I am not able to find the view files in the repo.

**Comment by lveillard** [comment]
The c is actually "ctrl + k" but I would remove it (it does not even work in Chrome) and maybe replace it by a tool tip later.

Nice lib btw 👀

**Comment by rayepps** [comment]
Hey @Starboy-Sharma thanks for the issue! I forked the best open source docs repo I could find (tailwind) and just hacked stuff out of it until it was just the little bit I needed for Radash. I'm disappointed to hear things are working just right but not suuuuuper surprised. 

If you could fix this that would be epic. I'm guessing you have a windows machine? It's trying to show `ctl+c` but it's getting messed up.

Let me see if I can find the right locations in the source for you to look at.

**Comment by rayepps** [comment]
> Nice lib btw 👀

Thank you @lveillard !!! Means a lot!

**Comment by rayepps** [comment]
Ok @Starboy-Sharma I think [this (NavSearchButton.js)](https://github.com/rayepps/radash-docs/blob/master/src/components/NavSearchButton.js) is the file you're looking for. There is some logic above it you might also be interested in where it's rendered [here (SidebarLayout.js)](https://github.com/rayepps/radash-docs/blob/master/src/layouts/SidebarLayout.js#L103)

**Comment by Starboy-Sharma** [comment]
Okay let me try thanks @rayepps

**Comment by rayepps** [comment]
I made an issue for this in the [radash-docs](https://github.com/rayepps/radash-docs) repo. Gonna close it here just so the issues on radash are just for radash and all the docs issues are on the docs repo. Happy to keep working with you on it over there! 😄
