### ISSUE TITLE
Would you be up to add a Recursive category?

### ISSUE THREAD

**Issue by lveillard** [rayepps/radash#19]
For functions like deepOmit or deepFind.  Would this kind of functions fit with radash?

**Comment by rayepps** [comment]
I think a `deep` function could be really interesting. Maybe something like `deep(tree, x => x.child, child => child.name)`. I'm spitballing here, but an abstraction that would let you easily create your own omit or find behavior while taking care of the recursive part.

Thoughts?

**Comment by lveillard** [comment]
Not sure if I understood the example but a recursive generator function would be indeed a funny concept to try. 

Some function we i can think of to try 
- deepOmit
- deepSort
- deepTransform (to use Key and Value)
- deepReduce

for example deepOmit could be something like => 
`deep( o => omit(o, '__typename), tree)`

The deep function should specify:
- What to do with the object
- What to do with regular values
- What to do with arrays
- What is the level of "deepness"

To be honest, my brain is not working fast enough to find a smart way to build this function, but I like the idea!


On the other hand, i was just suggesting a category where we offer the most used recursive functions

**Comment by rayepps** [comment]
> On the other hand, i was just suggesting a category where we offer the most used recursive functions

What do you think those are? The omit, sort, transform/map, and reduce you mentioned?

I think I'm seeing two families of recursive functions here:
1. mutating. Functions like omit and transform would essentially mutate the tree (even if it isn't _actually_ mutated) and return a new tree with the changes--still a tree though.
2. mapping. Functions like reduce, in my mind, would produce a new result--not a tree.

Tell me a bit more about the deepSort case. Would it return an array of sorted _nodes_ or would it reorganize the nodes in the tree and return a tree?

Some thoughts in code form:
```ts
const traverse = <TNode> (
  node: TNode, 
  children: (node: TNode) => TNode[], 
  mapper: (node: TNode) => TNode = n => n
): TNode => {
  // get children using children(node)
  // for each child recur traverse
  // set child back to tree
  // return node
}
```

uses (using HTML DOM nodes as example):
```ts
// Omit
const withoutSpans = traverse(html.body, el => el.children.filter(c => c.tag !== 'span'))

// Transform
const allUppercase = traverse(html.body, el => el.children, el => {
  if (el.innerText) el.innerText = el.innerText.toUpperCase()
  return el
})
```

There are some glaring issues, like:
- `//set child back to tree` this may need to be another function that's passed. Depending on the tree this could be very different.
- In the Transform example `el.innerText = el.innerText.toUpperCase()` this would actually mutate the dom node, a likely common problem. It would be good to have some way to _copy_ a tree node of any kind.
- This doesn't solve for reduce. A similar function (or maybe just extending this one) could be implemented.

**Comment by rayepps** [comment]
It's very rare that I work with anything recursively so if this is your area @lveillard please, teach me all the things.

**Comment by shahyar** [comment]
This could be pretty useful when traversing deep objects for mapping or reducing. See the `traverse` package's `map` and `walk` methods: https://github.com/Develatio/traverse-v2/blob/master/index.js

**Comment by rayepps** [comment]
The traverse lib is really interesting. I'd love to implement the same tools in Radash without the context or prototype code.

**Comment by lveillard** [comment]
That traverse-v2 is a nice example, the problem is that is not immutable. I think it could be a nice addition for radash.

I agree on the classification, but maybe a different naming
Traverse/transform: Object => Object
Fold/Reeduce: Object => Array

The deepSort I was imagining it as a function that orders every array or every array coming from a particular path name. For example
`{array: [1,7,2,5], b: {array: [9,1,5,2] }}` => `{array: [1,2,5,7], b: {array: [1,2,5,9] }}`

That could also be arrays of objects => 
```deepSort(
  {
  obj: myObj, 
  fx: (x,y)=>(x.totalBooks> y.totalBooks), 
  paths: ['authors']
  }
)
```

Not my area yet but I'm doing lots of recursion lately

**Comment by rayepps** [comment]
I'm gonna close this for now since there hasn't been any activity for a while. Recently chatting with @gquittet about creating a traversing function to convert existing functions into ones that a _deep_ behavior. Might be some crossover here.

https://github.com/rayepps/radash/pull/286#issuecomment-1608397517
