### ISSUE TITLE
Add index to `select`

### ISSUE THREAD

**Issue by mstykow** [rayepps/radash#197]
The mapper used by `select` should receive as argument the index of the element that is being mapped, in addition to the actual element being mapped.

**Comment by rayepps** [comment]
Thanks for bringing this up @mstykow 🙏  great point, I'll release a fix with this today.

**Comment by rayepps** [comment]
This is now available in v10.3.0 🎉

**Comment by mstykow** [comment]
Awesome! Thanks for adding that so quickly @rayepps.
