### ISSUE TITLE
Feedback about the docs

### ISSUE THREAD

**Issue by lveillard** [rayepps/radash#20]
First of all, congrats on the lib, some of the functions are even mind blowing :)

Just reviewing the doc. Not sure if the repo is public but i don't see it so here i go :)

0) Ctrl + C in windows  does the equivalent to ctrl + K, so i'm unable to copy text

1) 
Boil => Not sure about its naming 🤔

2)
![image](https://user-images.githubusercontent.com/29461076/186839261-d36005fe-0436-4e4d-ace8-3de605e21512.png)
I would probably use an array with 6 items so it is easier to understand the way this function packages items

3) 
counting =>  I would call it groupCount

4)
flat => Not sure why having this one. Radash is supposed to be "modern". What is the advantage agains native [].flat()?

5) 
![image](https://user-images.githubusercontent.com/29461076/186841206-f985b23d-762c-4126-bb2c-1417081dc0e7.png)
Should include Zues, and i guess it's a typo should be Zeus 🤔

6)
![image](https://user-images.githubusercontent.com/29461076/186842440-2350af62-fa28-4780-92d3-6295c03058df.png)
output should be: `//[{name: "Marlin" weight: 105}, {name: "Trout", weight: 13}]`

[...]

Checking the rest of the docs there are a lot of little issues like this. Specially in the output.

Also the playground is loading an older version of radish and not working!

**Comment by rayepps** [comment]
@lveillard thanks for the feedback! The repo is public you can check it out [here](https://github.com/rayepps/radash-docs).

> some of the functions are even mind blowing :)
I might have to quote you on this 😉 It's very kind!

1. The name `boil` could be totally misleading, I'm open to that possible reality. In my mind, I think of it like 'cooking off' all unwanted values. Do you have an other ideas?
2. Good point on the `cluster` example, I'll make this change
3. For `counting` I'm using this as a noun. I actually call the object returned a 'counting'. It could be just me that does this but it should be everyone :p this is such a common object to work with as engineers I want a name for it.
4. Ya great point about `flat`, in the beginning, I had a single file I would copy and paste from project to project with all these functions (well most of them, it's grown a bit) that I would use. One team wanted to use it as a package but only if they could replace Lodash completely. They used Lodash a lot. So, I had to make some concessions to get Radash in. This was one of them.
5. I will fix the typo!
6. I was trying to be brief. I should find a better way to provide examples. I'd like to have an in browser REPL soon. I'll write out the full value.

On the matter of little issues and typos, ya... all I can say is I did not expect this much enthusiasm and did not prepare Radash to be presented to the entire community 😅 I genuinely appreciate all the help from everyone to clean it up!

I'll also be fixing the playground link today.
