### ISSUE TITLE
Shift Method

### ISSUE THREAD

**Issue by Mostafa-Mohammadi** [rayepps/radash#207]
I have started to contribute and noticed that there is no page for the Shift method in the Array category on documentation.

Please update it.

**Comment by matteosacchetto** [comment]
The repo with the documentation is the following: https://github.com/rayepps/radash-docs

**Comment by Mostafa-Mohammadi** [comment]
> The repo with the documentation is the following: https://github.com/rayepps/radash-docs

Check this out https://radash-docs.vercel.app/docs/getting-started

**Comment by matteosacchetto** [comment]
Yes, I've seen it is missing.
What I meant is open the issue on the docs repo instead of here

Cheers

**Comment by Mostafa-Mohammadi** [comment]
> Yes, I've seen it is missing. What I meant is open the issue on the docs repo instead of here
> 
> Cheers

Do you have any information about the implementation of documentation? 
I have several questions about that.

**Comment by matteosacchetto** [comment]
Unfortunately, I have no info on that. For details related to the documentation wait for @rayepps

**Comment by rayepps** [comment]
I'm currently working on new docs that are simpler to manage and live in the radash repo.

Until then, if you wanted to add a shift page to the docs app you're looking for the `src/pages/docs` directory to add a new docs page and the `src/navs/documentation.js` file to add that page to the sidebar.

**Comment by Mostafa-Mohammadi** [comment]
> I'm currently working on new docs that are simpler to manage and live in the radash repo.
> 
> Until then, if you wanted to add a shift page to the docs app you're looking for the `src/pages/docs` directory to add a new docs page and the `src/navs/documentation.js` file to add that page to the sidebar.

Sure, I will do that
