### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by donnysim** [rayepps/radash#21]
So I've skimmed the documentation and there's missing `debounce` menu entry, which I thought was not implemented but found a link in medium article. Also the version says v7 but it's actually v2?

Other note, might be related more to code, shouldn't `camal` be named `camel`? it's usually called camel case not camal case afaik.

The biggest thing from docs right now I'm missing is the list of arguments, the examples are nice but you have to dig into the code and read those typescript types to understand what options it accepts and what they do or scour multiple samples to see what usage there is, like `memo`. It would be nice to open up with here's the `memo` function, and here's the arguments it accepts and their value (config options) etc.. lodash is a decent starting sample, like [throttle](https://lodash.com/docs/4.17.15#throttle) though the options are a bit messy. Only then provide the samples.

**Comment by rayepps** [comment]
Thanks for the feedback, I'll add debounce to the navigation and rename camal (@danish-mehmood has already done the heavy lifting there).

On the docs having the arguments documented, I agree! It's a good callout. It's just gonna take me a bit of time to get that one done. Hopefully by next weekend thought.

**Comment by rayepps** [comment]
[This PR](https://github.com/rayepps/radash-docs/pull/5) has fixed everything brought up here except the documentation of function arguments. I've opened a separate issue for that in the radash-docs repo.
