### ISSUE TITLE
The case about `get`

### ISSUE THREAD

**Issue by donnysim** [rayepps/radash#22]
So I understand why you went the way you did with `get`, but big part of the string path approach is you don't need to access the nested data to find a value, for me it's invaluable as I've encountered many cases where you know, say a dot notated string path and you want the value without having to manually traverse it. For example there are validators that return string path key e.g. `children.0.name` failed and you want to get the value from said key, or sometimes you have to traverse DOM elements and build an object path to read or write, which current approach makes it impossible and requires manual handling. 

Also the current approach of
```js
const fish = {
  name: 'Bass',
  weight: 8,
  sizes: [{
    maturity: 'adult',
    range: [7, 18],
    unit: 'inches'
  }]
}

const maxAdultSize = get(fish, f => f.sizes[0].range[1])
```
for me looks nothing more than
```js
const maxAdultSize = fish.sizes?.[0].range?.[1];
```

Would this be something you'd be willing to look at?

**Comment by rayepps** [comment]
This is interesting, thanks for bringing it up. You're totally correct, the two examples are exactly the same. It's this reason that the `get` function is my least favorite function in the library. However, early users said they needed an alternative for Lodash's `get` function to make the switch so I made it--with a bit of protest.

I see what you're saying about the use case. It's a totally valid problem I'd love to solve. The issue for me is around the typing, there is no way to strongly type the nested string (that I'm aware of). I've been bit so many times by Lodash using `get(obj, 'name')` when you change `obj.name` to `obj.firstName` and don't know you broke something.

I'm down to implement this, maybe in a new function specifically branded as a bit dangerous. A `dynamic` function? I'd prefer to get the types to work but if this is a deal breaker for people to use the library it can be added.

**Comment by donnysim** [comment]
I'm not really a typescript user, used to be but it just never paid off with all the extra effort and work being put into typings instead of just building the actual feature and there's never real guarantee that types will match anyway on runtime so I can't really comment on the typings, though I do love when libraries provide typings to improve the IDE experience and all. 

I'm sure some typescript gurus would be able to figure something but I'm not sure what real benefit it would bring, because if you know what you want then just access it directly, the string path helpers usually is used via dynamically generated paths so most of the time you don't know what it will be anyway.

**Comment by rayepps** [comment]
It's so funny you say that, I used to say the exact same thing. It's a fair enough point of view.

I'd like to make the function. I'm looking at Lodash's `get`, can we assume the input is an object? Looks like the Lodash `get` will accept object, array, number, string, anything really.

**Comment by donnysim** [comment]
I think you'd end up supporting them anyway? for example accessing `children.0.name` where `children` value would be null or a number, you'd still safeguard against crashing and return undefined/fallback value in that case, the only difference would be it's not the initial value but the following. Most likely something like `!isArray && !isObject return fallback` type of thing.

**Comment by rayepps** [comment]
I did the research on Google and it's clear that this is a function that the community needs in a Lodash successor. There's an abundance of questions about it on StackOverflow and the best answers just point to Lodash's get function. I'm actually surprised someone hasn't created a robust single-function library for this.

I'd like to call it something other than `get`:
- `reach`
- `mine`
- `x`
- `dynamic`
- `selector`
- `pull`

I'm going to spec out the use cases here, tell me if you see anything missing or incorrect.
```ts
const person = {
  name: 'Jay',
  pets: [{
    name: 'Bently',
    type: 'dog'
  }]
}

const selector = (data: any, path: string, fallback?: any): any => {
  // TODO: Implement
}

// Basic
selector(person, 'name') // => Jay
selector(person, 'age', 0) // => 0

// Array access
selector(person, 'pets[0].type') // => dog
selector(person, 'pets[1].type') // => undefined
selector(person, 'pets[0]') // => { name: Bently, type: dog }

// Other Array access
selector(person, 'pets.0.type') // => dog
selector(person, 'pets.1.type') // => undefined
selector(person, 'pets.0') // => { name: Bently, type: dog }

// Bad inputs
selector(0, 'pets') // => undefined
selector(null, 'pets', []) // => []

// Questionable?
selector('hello', '0') // => h
selector(['h'], '.0') // => h
```

**Comment by donnysim** [comment]
If you're looking at lodash implementations then the docs kind of lack the full picture it supports, it can be:
```js
// objects
object.name
[object].name
[object][name]
object[name]
object.[name]
['object', 'name'] // array of keys

// arrays
0.name
[0].name
[0][name]
0.[name]
['0', 'name'] // array of keys
```

It's quite flexible in the way you can pass the path, though personally I extremely rarely used the bracket syntax, There are very rare cases where the the object key also contains a dot, where lodash handles it only if passed via array:

```js
get({'key.with.dot': true}, '[key.with.dot]') // undefined
get({'key.with.dot': true}, ['key.with.dot']) // true
```

which from first look you'd expect the bracket syntax to also work if we'd looks at access patterns of js like `object['key.with.dot']` etc..

I can't say which syntax gets what use, though I feel that dot syntax is usually the most used, with rare cases of array style where "escaping" keys with dots is necessary.

For naming I don't know 😄all of them feel weird compared to `get`. For libraries there are a few: https://www.npmjs.com/search?q=dot-path
though I mostly prefer not having to install a new library I'm not familiar with where it might pull even more dependencies etc..

**Comment by rayepps** [comment]
I've been thinking about this the past few days, sort of dreading implementing some _pseudo string parser_ but today it hit me how incredibly simple it could be. I put up PR #57 , checkout the unit tests and see if it covers what you need @donnysim 

It doesn't support the array input, although it could easily, that just seems weird to me. I'm really trying to to parity Lodash on the freaky stuff they do. Finding that line can be a challenge though so let me know what you think.
