### ISSUE TITLE
Object function `zip` missing

### ISSUE THREAD

**Issue by manuelhenke** [rayepps/radash#234]
According to the [documentation](https://radash-docs.vercel.app/docs/object/zip), there should be a `zip` function for objects. But in the source code, is only a `zip` functions for [arrays](https://github.com/rayepps/radash/blob/master/src/array.ts) and none for [objects](https://github.com/rayepps/radash/blob/master/src/object.ts).

**Comment by rayepps** [comment]
Hey @manuelhenke thanks for bringing this up. We did some renaming and moving around of the zip function recently so the zip documentation your seeing in the object module shouldn't be there. I've fixed it 👍
