### ISSUE TITLE
Typing of `get` broken

### ISSUE THREAD

**Issue by mstykow** [rayepps/radash#239]
**Issue description:** The return type of `get` is `K | null` where `K` is the type of the default value. This means that I can never make the return value non-nullable even when providing a non-nullable default value.

**Expected:** When I provide a default value to `get`, then the return type should be the type of the default value without any union members such as `null`. Only when no default value is provided should the return value always include `null` (or `undefined` depending on preference).

**Side note:** It would be even better if we inferred the return value from the first argument from which the get-function derives the result via the path (second argument). Only if this inference leads to null/undefined, should the default value type even come into play. But this is more work to implement.

**Comment by rayepps** [comment]
Hey @mstykow 👋 this is a great callout, I'll make a fix this weekend.

About the side note, I would love it if the typing was robust enough to infer the return type from the string path. The [ts-toolbelt](https://github.com/millsp/ts-toolbelt) library has a `Path` type (and some other useful types) I've considered either importing or copying. I personally wouldn't know where to start to dynamically infer the type in that situation 😅

**Comment by rayepps** [comment]
This is what I've come up with. What do you think @mstykow ?

```ts
get<TDefault = unknown>(
  value: any,
  path: string,
  defaultValue?: TDefault
): TDefault

get({}, 'enemies.0.power') // => unknown
get({}, 'enemies.0.power', null) // => unknown
get({}, 'enemies.0.power', undefined) // => unknown
get<string>({}, 'enemies.0.power') // => string
get({}, 'enemies[0]power', 22) // => number
get<number>({}, 'enemies[0]power', 22) // => number
```

**Comment by mstykow** [comment]
This looks like a nice improvement @rayepps! Thank you so much. :)

**Comment by apstanisic** [comment]
Also, this function does not respect returning `undefined` as default value.
[runkit error example](https://runkit.com/embed/k1v6klfm97xx)
Example:
```js
var radash = require("radash")
let obj = {a: {b: {c: "hello"}}}
let result = radash.get(obj, 'a.b.c.d',undefined)
console.log(`isUndefined ${result === undefined}`)
console.log(`isNull ${result === null}`)
```
