### ISSUE TITLE
Alias `try` as `tryit`

### ISSUE THREAD

**Issue by rayepps** [rayepps/radash#24]
## Problem
Because `try` is a reserved word I find myself doing this a lot `import { try as tryit } from 'radash'`. It's annoying. I shouldn't have to alias it myself considering its obviously a reserved word -- everyone has to alias it (unless they import the whole library `import * as _ from 'radash'`).

## Solution
Add an aliased export to the `src/index.ts` so it can be imported as `tryit`.
```ts
export {
  tryit as try,
  tryit
} from './curry'
```

**Comment by suchangv** [comment]
Why don't remove `try`? I am the first time to use this library, it really confused to me.
