### ISSUE TITLE
`trim` throws on edge cases

### ISSUE THREAD

**Issue by apstanisic** [rayepps/radash#250]
[runkit link](https://runkit.com/embed/7mlm73yz212f)

Run bellow code, it throws:
```js
radash.trim(" __-_ hello", "_- ")
```
Error
```
SyntaxError: Invalid regular expression: /^[_- ]+|[_- ]+$/: Range out of order in character class
```
I can open PR

PS Are you open for adding `trimStart` and `trimEnd`?

**Comment by rayepps** [comment]
Oh wow, that's an awful bug. I think `trimStart` and `trimEnd` would be great additions 👍
