### ISSUE TITLE
`get` function does not support `undefined` as a default value

### ISSUE THREAD

**Issue by apstanisic** [rayepps/radash#253]
Function does not respect returning `undefined` as default value.
[runkit error example](https://runkit.com/embed/k1v6klfm97xx)
Example:
```js
var radash = require("radash")
let obj = {a: {b: {c: "hello"}}}
let result = radash.get(obj, 'a.b.c.d',undefined)
console.log(`isUndefined ${result === undefined}`)
console.log(`isNull ${result === null}`)
```

**Comment by rayepps** [comment]
Oh rad, didn't realize you had made a separate issue for this. There's a PR up with this fix right now, will have it out in a TBD version soon.
