### ISSUE TITLE
Unable to set boolean value false to object using "set" function

### ISSUE THREAD

**Issue by tqiqbal** [rayepps/radash#257]
For example,
import { set } from 'radash'

const obj = { id: true }
let obj2 = set(obj, id, false)
console.log(obj2)
// => { id = true }

**Comment by mattrothenberg** [comment]
Confirmed with falsy number values, too, e.g., 
```
set({}, 'foo', 0);
// => {} 
```

**Comment by intrueder** [comment]
Hey @rayepps, could you please look into it?

**Comment by rayepps** [comment]
Should be resolved by #263 which will get published today in [v11.0.0](https://github.com/rayepps/radash/releases/tag/v11.0.0)
