### ISSUE TITLE
Feature Request: cloneDeep

### ISSUE THREAD

**Issue by KareemDa** [rayepps/radash#306]
A simple description for the simple title: can you create a new helper to deep clone nested objects ?

**Comment by JacobWeisenburger** [comment]
Would this work for you?
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**Comment by lake2** [comment]
same issue + 1

**Comment by hesetiema** [comment]
structuredClone doesn't support the Function deep clone.
