### ISSUE TITLE
`chain` function can't infer data type

### ISSUE THREAD

**Issue by fResult** [rayepps/radash#339]
From the `chain` function in `src/curry.ts` file, it has no type inferred for this function.
https://github.com/rayepps/radash/blob/c3c9dac9c5da8102a8c62b1afbbb7efb9c64c31e/src/curry.ts#L5-L10

When I use the `chain` function, it returns `any[]`.  
Actually, I expected the return type should be `Uppercase<string>[]`.

```ts
interface Person {
  name: string
  age: number
}

const persons: Person[] = [
  { name: 'Aa', age: 10 },
  { name: 'Ba', age: 20 },
  { name: 'Ca', age: 30 },
]

function upperCase(text: string): Uppercase<string> {
  if (!text) return ''
  return text.toUpperCase() as Uppercase<string>
}

function getName<T extends { name: string }>(item: T): string {
  return item.name
}

const upperNames = persons.map(chain(getName, upperCase))
          // ^   <--- any[]
```

So, I have to define the type for the `upperNames` variable.
```ts
const upperNames: Uppercase<string>[] = persons.map(chain(getName, upperCase))

// OR

const upperNames = persons.map<Uppercase<string>>(chain(getName, upperCase))
```

I want the type inferred for the `chain` function, that makes me annoyed a bit. 🥹  
Anyone can make it able to infer?

**Comment by rawnly** [comment]
same here, even with the basic example seem that neither `chain` or `compose` can infer any type

```ts
const gen = () => 0;
const addOne = (x: number) => x + 1;

const g = chain(gen, addOne);
```

![CleanShot 2023-09-03 at 19 57 13](https://github.com/rayepps/radash/assets/16429579/330bdd4f-17f5-4c95-8fc9-1fad50c86105)

**Comment by fResult** [comment]
> same here, even with the basic example seem that neither `chain` or `compose` can infer any type
> 
> ```ts
> const gen = () => 0;
> const addOne = (x: number) => x + 1;
> 
> const g = chain(gen, addOne);
> ```
> 
> ![CleanShot 2023-09-03 at 19 57 13](https://private-user-images.githubusercontent.com/16429579/265280862-330bdd4f-17f5-4c95-8fc9-1fad50c86105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTMxMzEsIm5iZiI6MTcwMTc1MjgzMSwicGF0aCI6Ii8xNjQyOTU3OS8yNjUyODA4NjItMzMwYmRkNGYtMTdmNS00Yzk1LThmYzktMWZhZDUwYzg2MTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA1MDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMzFkNDc1MzQwMjljYjg1ODZmN2QyNjhlOTVlMzM1YWM5ZGMxYmFhNzk2MmRmYzAwMWIyMTBiOTViMGE1ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-UWCW02_Y2q4lBVCs-XRNwKsAAhotBUvF4fed1C_vgs)

I already fixed this.  
You can check this pull request.  
https://github.com/rayepps/radash/pull/370

**Comment by fResult** [comment]
I have a question...  
How can I finish this package.json?

**Comment by fResult** [comment]
@rayepps
This issue relates to [PR#370](https://github.com/rayepps/radash/pull/370).\
Please don't forget to close the issue. 😄
