### ISSUE TITLE
mapValues cannot be used with partial records due to Record argument type

### ISSUE THREAD

**Issue by osdiab** [rayepps/radash#354]
`mapValues()` expects a `Record<Key, Value>`. But other stuff in Radash returns `Partial<Record>>`s like `group()` (see #351 ). So you can't compose these together without casts because partial records are not assignable to records.

https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&allowUnreachableCode=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&useUnknownInCatchVariables=true&suppressImplicitAnyIndexErrors=true&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBAbzgcyhArmANHEBDMANTwBt0BTAZzgF84AzNEOAIijwBM9KALFgbgBQgmAE8w5OMTKSAvKzws4AH1YAjJapYBjFoO0QAdpXgA3UhUoAuKRfIBtALpx5T-UZNwwabVUrkOaUsXXAIgqgAKVAwwCPMZShxTFwA+OFMASiS7VLgAAwAJYDgAEgR4iho8jP4gA

**Comment by brettbedarfmw** [comment]
Did you find a solution? This is causing problems for me

**Comment by osdiab** [comment]
Nope just had actually made another issue that's basically the same so I closed this one. In my codebase I just use a different pattern to achieve the same effect but it's still annoying
