### ISSUE TITLE
Why is cloneDeep not implemented

### ISSUE THREAD

**Issue by xoxosos** [rayepps/radash#394]
It has a high usage rate

**Comment by narukeu** [comment]
JS now provides the native function structureClone(), which I think is better than any function implemented in JS.

**Comment by xoxosos** [comment]
> JS now provides the native function structureClone(), which I think is better than any function implemented in JS.
> 
> 现在新的浏览器和 Node JS 可以用 structureClone() 啊，原生 API，比 JS 实现一个要好多了。

嗯 ，structuredClone()基本上能满足深拷贝的需求了
