### ISSUE TITLE
IsNumber function returns false for floats

### ISSUE THREAD

**Issue by jovanamatk** [rayepps/radash#43]
`IsNumber` function currently returns `false` if you pass it a non-integer value. Basically, it checks if a number is an integer.

![image](https://user-images.githubusercontent.com/63621526/187554997-52fcd5ac-0b8f-420b-a15b-493a9f16944c.png)

This function should either return `true` for all numbers or be renamed to `isInteger`. 

From [MDN docs](https://developer.mozilla.org/en-US/docs/Glossary/Number): `The JavaScript Number type is a double-precision 64-bit binary format IEEE 754.`
#
https://github.com/rayepps/radash/blob/b1e2a8b16de764d2c860e01332130002b2e1ce3a/src/typed.ts#L21-L25

**Comment by rayepps** [comment]
Great catch @jovanamatk 👍 I'd like to have an `isInt`, `isFloat` as well as an `isNumber` function that unions the more int/float check.

This is pretty bad... I'll make a change and fix tonight.
