### ISSUE TITLE
Feature - map: asyncMapFunc should have item and index?

### ISSUE THREAD

**Issue by welpie21** [rayepps/radash#55]
Good morning,

I wanted to use radash in my react front-end application and i missed a nice feature what could potentially be added into the map function.

in the map function parameter: `asyncMapFunc: (item: T) => Promise<K>` if it's possible to addition something like this: `asyncMapFunc: (item: T, index: number) => Promise<K>`

I forked the repository and made some edits. If you find it a nice addon to the map function i can create a pull request if you want.

In waiting for you reply wish you a nice day.

**Comment by rayepps** [comment]
Hello @welpie21 thanks for taking the time to make an issue! I think adding an `index` argument to the callback is a great idea 👍 

If you make a PR with the change I'd be happy to merge it.

**Comment by welpie21** [comment]
As soon as i will be home i will create a merge request.
