### ISSUE TITLE
'pick' picks provided key even if it is not in the object

### ISSUE THREAD

**Issue by bogem** [rayepps/radash#67]
Hello @rayepps! Thanks for this awesome library! 
I found an issue with `pick` function. It picks the keys that are not even in the object:

Code: `pick({ a:1, b:2 }, ['c'])`
Actual return value: `{ c: undefined }`
Expected return value: `{}`

Lodash's pick doesn't pick the key that is not in object. I expect that too.
Is it intended or it should be fixed? Thanks!

**Comment by rayepps** [comment]
Hey @bogem , sorry for such a late reply. Thanks for bringing this up, it is not intended. I'll put in a fix today.

**Comment by rayepps** [comment]
I seriously over estimated my available time to do this 😅

**Comment by matteosacchetto** [comment]
@rayepps if you want I can open a PR for this

**Comment by rayepps** [comment]
@matteosacchetto that would be awesome 🏆

**Comment by matteosacchetto** [comment]
Working on it right now 😉

**Comment by rayepps** [comment]
This has been fixed and published 🚀 in version `8.0.2`
