### ISSUE TITLE
Typing for `sift` function

### ISSUE THREAD

**Issue by cadam11** [rayepps/radash#68]
Right now, the `sift` function returns type `T[]` which could be inferred as a type that includes `undefined` or `null` (which are omitted from the actual return value, by design). The outcome is that `sift` doesn't work well as a type guard. Would be great if it would narrow the return type to `NonNullable<T>[]`.

I'm happy to open a PR if it would be welcome.

**Comment by rayepps** [comment]
Hey @cadam11 thanks for bringing this up! I really like the idea of improving the typings on sift like this. I whipped up the change, it was super easy, just adding the return type definition. I've actually never used `NonNullable` before so I wanted to play with it a bit.

Let me know what you think! If I'm off the mark somehow just let me know.
