### ISSUE TITLE
Add the `sample` function

### ISSUE THREAD

**Issue by deivuss331** [rayepps/radash#70]
Hi,

I'm missing the `sample` function from lodash. The purpose of this function is to return a random element from an array.
Take a look at the reference: https://lodash.com/docs/4.17.15#sample

It should work like this:

```javascript
_.sample([1, 2, 3]) // 3
_.sample([1, 2, 3]) // 1
_.sample([]) // undefined
```

Let me know what do you think. I can send a PR to this one.

**Comment by deivuss331** [comment]
I've sent a PR #71

**Comment by GadQ** [comment]
There is a draw function which does that, except it returns null on empty array:
https://github.com/rayepps/radash/blob/master/src/random.ts#L14

**Comment by deivuss331** [comment]
@GadQ I see that now... It's misleading that this function is under "Random" instead of "Array". Closing the issue

**Comment by RayPS** [comment]
You can draw more than single item in both Lodash and Undersocre:
'''
_.sample([1, 2, 3], 2)
// Draw 2 items
'''
Can you also implement the draw size?
