### ISSUE TITLE
Potential perf issue 

### ISSUE THREAD

**Issue by dragansmlinus** [rayepps/radash#78]
Why the destructuring assignment is needed here (and on some other places):
https://github.com/rayepps/radash/blob/master/src/object.ts#L34

```
/**
 * Map over all the keys of an object to return
 * a new object
 */
export const mapKeys = <
  TValue,
  TKey extends string | number | symbol,
  TNewKey extends string | number | symbol
>(
  obj: Record<TKey, TValue>,
  mapFunc: (key: TKey, value: TValue) => TNewKey
): Record<TNewKey, TValue> => {
  return Object.keys(obj).reduce(
    (acc, key) => {
      acc[mapFunc(key as TKey, obj[key])] = obj[key];
      return acc;
    },
    {} as Record<TNewKey, TValue>
  )
}
```

might be more performant. Or, maybe this one:

```
export const mapKeys = <
  TValue,
  TKey extends string | number | symbol,
  TNewKey extends string | number | symbol
>(
  obj: Record<TKey, TValue>,
  mapFunc: (key: TKey, value: TValue) => TNewKey
): Record<TNewKey, TValue> => {
  const acc = {} as Record<TNewKey, TValue>;
  const fn = ([key, value]) => {
    acc[mapFunc(key as TKey, value)] = value;
  };
  Object.entries(obj).forEach(fn);
  return acc;
}
```

**Comment by rayepps** [comment]
Hello @dragansmlinus 👋 I don't think I understand the issue your describing. Could you give a bit more information? What 'destructuring assignment' are you referring to?

**Comment by matteosacchetto** [comment]
Ok, so I think I got what the OP meant
The question is: "Why, in `reduce` functions (or similars) are you returning a new accumulator and destructuring the previous one, instead of assigning the keys/values to the accumulator you already have?"

Here is an example of the issue mentioned by the OP
```ts
return Object.keys(obj).reduce(
    (acc, key) => ({
      ...acc,
      [obj[key]]: key
    }),
    {} as Record<TValue, TKey>
  )
```
as you can see, here we are destructuring acc (`...acc`) and returning a new acc at every iterations, while what the OP is suggesting is a version withouth destructuring
```ts
return Object.keys(obj).reduce(
    (acc, key) => {
      acc[obj[key]] = key
      return acc
    },
    {} as Record<TValue, TKey>
  )
```

**Comment by matteosacchetto** [comment]
Based on a preliminary analysis, the second version seems to be faster by 2x or more, but I will try to write a better benchmark to validate so

**Comment by MarlonPassos-git** [comment]
@matteosacchetto  Really, the bigger the number in the array, the bigger the difference between the two.


to make it easier, I took it based on your test and put it here on jsben.

Of course, I didn't see everyone who will exucult this function with an array of 1000 elements, but even with simpler arrays of 5 keys we already see a difference of being 2x faster and this is scaling.

https://jsben.ch/qnk3u

5 objects
func1 = 100% (2941513)
func2 = 43.3% (1327926)

10 objects
func1 = 100% (2252751)
func2 = 27.39% (610724)

50 objects
func1 = 100% (428450)
func2 = 9.84% (42159)

100 objects
func1 = 100% (265228)
func2 = 0.51% (1362)

500 objects
func1 = 100% (53844)
func2 = 0.08% (42)

One thing that sticks in my mind is that if we make this change (which in my opinion is valid) we should be creating a test jest to always validate that the next changes in this function will be below this new level of performance, and at this point I really I don't have much experience. Or maybe this thing of creating a performance test wasn't even valid.

**Comment by matteosacchetto** [comment]
@MarlonPassos-git yeah, that's the same performance improvement I saw. Already with small objects it improves by 2x.

I agree that this change is valid and would drastically improve performance across the board of functions included in this library.

I do think it is a valid idea to have a sort of performance benchmark to prevent alterations which would reduce performance of the basic solution. I do not know though if something like this is possible though... Unfortunately I do not have any experience on this..

**Comment by MarlonPassos-git** [comment]
@matteosacchetto  a more agnostic way to test the performance of a function would be with performance.now().

I made this sketch, theoretically it would work fine. Everything would depend that the first time we were going to test the performance of a function manually we should set the value of limit.

As I never had to deal specifically with this type of test, I don't know if this would be the best way.
![image](https://user-images.githubusercontent.com/63638196/197362357-6232836d-f705-41c3-a84c-ca116d3229c2.png)

What do you think @rayepps  ?

**Comment by rayepps** [comment]
I love it.

For changing the code, I want to be mindful about how far we go down the performance rabbit hole to make sure we're not trading away the simplicity of Radash.

I'm a huge fan of adding a performance/benchmark regression to the CI. It might be a bit of work to setup but its all simple. I've setup some similar workflows in the past.
