### ISSUE TITLE
Provide ESM option with tree-shakable exports

### ISSUE THREAD

**Issue by dolsem** [rayepps/radash#79]
It would be nice to provide an ESM version of the package, especially for those who use bundlers like Webpack, and add `sideEffects: false` to `package.json`, so that if I, say, use `import { objectify } from 'radash'` in my code, my bundler only includes that function's definition in my bundle, without all the extra stuff.

**Comment by matteosacchetto** [comment]
Hi @dolsem, I was having the same Idea!

There is a discussion about this: #49, please feel free to share your ideas there, if you have any previous experience about how to handle a package with both ESM and CJS exports. I am trying to come up with an easy to maintain way to do so, but unfortunately these weeks I am a bit busy... Though I will come back to this as soon as I can! Hopefully in one week I will have time

Cheers,
Matteo

**Comment by dolsem** [comment]
Thanks @matteosacchetto!
