### ISSUE TITLE
Questions - Correcting typescript errors is something valid?

### ISSUE THREAD

**Issue by MarlonPassos-git** [rayepps/radash#84]
I started using radash and found it very cool. 
I was looking at the code to see if there was something for me to help and I debuted something, but I don't know if it's something valid.

I particularly don't like red things on the screen, I always try to correct the error or adjust the rule that causes it.
In this case I saw that in many cases in the tests you pass null values to check if the function will work as you expect. 
I really don't think it's necessary or recommended to change the typing of the functions themselves, but forcing a type to be able to open the test files and not see an error I think it's valid.

It may be silly of me, that's why I came to ask you your opinion on. And if you think it's valid, I may be doing a PR to correct these errors.

![image](https://user-images.githubusercontent.com/63638196/190828458-8d173d96-01f6-4cd3-9c67-ab215832c04c.png)

**Comment by rayepps** [comment]
Hey @MarlonPassos-git 👋 thanks for taking the time to bring this up! You bring up a very interesting point... I don't _love_ the red lines in the test files either so I'm open to the idea of casting types to make the squiggles go away.

If you made a PR to cast all the types on the red lines I would approve and merge it 👍
