### ISSUE TITLE
Cancel debouce

### ISSUE THREAD

**Issue by hlspablo** [rayepps/radash#87]
there is some way to cancel debounced function's execution?, this is a very useful use case and since this lib wants to replace lodash, a think this is a must have

**Comment by rayepps** [comment]
Hey @hlspablo thanks for bringing this up. I don't think I understand the use case. Can you maybe provide some pseudo code for what you're looking for? Just to help me understand :)

**Comment by hlspablo** [comment]
const req = debounce({ delay: 100 }, makeSearchRequest)


where req.cancel() cancel the makeSearchRequest execution if called before the delay. It can be very handy in a lot of scenarios.

**Comment by rayepps** [comment]
I see how this could be helpful, happy to build it (or merge a PR if someone else wants to build it) to support it.

One question, since I've never needed it personally, to make sure I understand the behavior: Should `cancel` cancel the next scheduled invocation or does it cancel all future invocations?

**Comment by hlspablo** [comment]
in a simpler implementation, should cancel all future invocations, maybe in the future it could evolve to cancel n invocations passed to cancel, but it think that cancelling all should help 99% of use cases.

**Comment by MarlonPassos-git** [comment]
@hlspablo I'm developing a beta version that solves this problem and I managed to solve it for both future and past debounces, but with that I have a doubt.
Would it be interesting to create a method that allows debounce to work again? Or know what his status is?

I'm looking at lodash and it has flush and pending methods. If you find it interesting, I can add it too.

**Comment by hlspablo** [comment]
@MarlonPassos-git I don't think that this complexity is necessary, make it work again is almost the same of calling the debounced func with new parameters. I like the ideia of implementing flush too, could be very useful to fire the debounced functions immediately. @rayepps what do you think?

**Comment by rayepps** [comment]
I like the idea of making it as simple as create and cancel. In a way, the debounce can be immutable. If you need to _pause_ you can cancel then create a new function when you want to resume.

**Comment by hlspablo** [comment]
A simple immutable debounce, with cancel and flush methods looks perfect to me.

**Comment by rayepps** [comment]
This is out and available in [v10.1.0](https://github.com/rayepps/radash/releases/tag/v10.1.0) 🚀
