### ISSUE TITLE
isString and TypeScript narrowing

### ISSUE THREAD

**Issue by charleskoehl** [rayepps/radash#98]
isString does not behave as a typeof type guard in TypeScript.

In this example, isString(str) should have the same type guarding effect as typeof str === 'string'

![image](https://user-images.githubusercontent.com/887025/194741041-2f190ddd-f6f6-4b55-a05a-4d3edb61c3d1.png)

**Comment by matteosacchetto** [comment]
It should be as easy as this:
```ts
export const isString = (value: any): value is string => {
    return typeof value === 'string' || value instanceof String
}
```
Simply add a TS guard as return type

Reference: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates

**Comment by rayepps** [comment]
Wow, I have never seen this _type predicate_ before, I didn't know this existed. I'd love to add this to all the `isN` functions in the typed module.

@matteosacchetto regarding your question, it seems valid both ways but I'd probably prefer `value is string`. For 99% of people I think this will be the happy path. For the 1% who need the value to be a `String` instance type they can cast it.

**Comment by matteosacchetto** [comment]
So, just to be on the same page, this is the solution you prefer, right?
```ts
export const isString = (value: any): value is string => {
    return typeof value === 'string' || value instanceof String
}
```

If so I will proceed and do a PR and add type guards to all `isN` methods

**Comment by rayepps** [comment]
Yes 👍 it would be awesome if you made a PR but I can also do it. I'd like to get it in for the `8.0.0` release with the ESM change (today or tomorrow)

**Comment by matteosacchetto** [comment]
I have a question on the `isN` functions:
```ts
export const isSymbol = (value: any): value is symbol => {
  return !!value && value.constructor === Symbol
}
```
Why in some functions you didn't use `typeof` or `instanceof` like for `isString`?

**Comment by rayepps** [comment]
For each `is` check I used the most dependable check I could find on google, stackoverflow, and other libraries. Because Javascript is a _quirky_ language using `instanceof` is not always the most reliable way to check the type of a variable at runtime.

A good example is `isDate`, as mentioned in [this SO post](https://stackoverflow.com/a/643827) using `instanceof` on a Date will fail when passing across frame boundaries.

There are lots of little quirks like that we want to account for.

**Comment by matteosacchetto** [comment]
Ok, good to know, thank you for the details 😉

**Comment by matteosacchetto** [comment]
@rayepps did a PR for this

**Comment by charleskoehl** [comment]
Thanks guys I didn't get notifications of this activity or I would have responded sooner.
